version: '3.9'
services:

  ms-db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    networks:
      - ms_network
    expose:
      - '3308'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
  ms12-ms:

networks:
  ms_network:

#  redis:
#    image: redis:6.2-alpine
#    ports:
#      - '6379:6379'
#  mongodb:
#    container_name: ms11-mongo
#    image: mongo:5.0
#    ports:
#      - '27017:27017'
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=Password


